### PR TITLE
Check if annotations are empty before setting them

### LINKED ISSUE #84: controller exits on `Certificate` with generated name
**What steps did you take:**
Apply:
```yaml
apiVersion: secretgen.k14s.io/v1alpha1
kind: Certificate
metadata:
  generateName: root-ca-cert-
  namespace: default
spec:
  isCA: true
```

**What happened:**
The secretgen-controller deployment dies:
```
secretgen-controller-78f5844ddb-fvn26 secretgen-controller E0706 13:07:02.746908       1 runtime.go:78] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller goroutine 387 [running]:
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/runtime.logPanic({0x131cda0, 0x164d9d0})
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:74 +0x99
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000289000})
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:48 +0x75
secretgen-controller-78f5844ddb-fvn26 secretgen-controller panic({0x131cda0, 0x164d9d0})
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      runtime/panic.go:1038 +0x215
secretgen-controller-78f5844ddb-fvn26 secretgen-controller github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator.GenerateInputs.Add({{0x13f7240, 0xc00049ca80}}, 0x0)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator/generate_inputs.go:23 +0x65
secretgen-controller-78f5844ddb-fvn26 secretgen-controller github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator.(*CertificateReconciler).createSecret(0xc000776a50, {0x16799b8, 0xc00089a2a0}, {{0x0, 0x0}, {0x14a0bf4, 0x9}, {0x0, 0x0, 0x0}, ...}, ...)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator/certificate_reconciler.go:119 +0x45e
secretgen-controller-78f5844ddb-fvn26 secretgen-controller github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator.(*CertificateReconciler).reconcile(0xc000776a50, {0x16799b8, 0xc00089a2a0}, 0x0)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator/certificate_reconciler.go:79 +0x29d
secretgen-controller-78f5844ddb-fvn26 secretgen-controller github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator.(*CertificateReconciler).Reconcile(0xc000776a50, {0x16799b8, 0xc00089a2a0}, {{{0xc00064f0e0, 0x138c9c0}, {0xc00064f0d0, 0xc000812340}}})
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator/certificate_reconciler.go:70 +0x395
secretgen-controller-78f5844ddb-fvn26 secretgen-controller sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00076f040, {0x1679910, 0xc0004ac4c0}, {0x1368e00, 0xc000289000})
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263 +0x303
secretgen-controller-78f5844ddb-fvn26 secretgen-controller sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00076f040, {0x1679910, 0xc0004ac4c0})
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235 +0x205
secretgen-controller-78f5844ddb-fvn26 secretgen-controller sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1({0x1679910, 0xc0004ac4c0})
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198 +0x46
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0x25
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fa4be29dcf8)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155 +0x67
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0, {0x16542e0, 0xc00089a120}, 0x1, 0xc0000af4a0)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156 +0xb6
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x2, 0x3b9aca00, 0x0, 0x80, 0x1000000020002)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133 +0x89
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext({0x1679910, 0xc0004ac4c0}, 0xc00057a0e0, 0x0, 0x0, 0x0)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0x99
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/wait.UntilWithContext({0x1679910, 0xc0004ac4c0}, 0xc000614c60, 0xc00014ef68)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99 +0x2b
secretgen-controller-78f5844ddb-fvn26 secretgen-controller created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:195 +0x4b0
secretgen-controller-78f5844ddb-fvn26 secretgen-controller panic: assignment to entry in nil map [recovered]
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      panic: assignment to entry in nil map
secretgen-controller-78f5844ddb-fvn26 secretgen-controller
secretgen-controller-78f5844ddb-fvn26 secretgen-controller goroutine 387 [running]:
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000289000})
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:55 +0xd8
secretgen-controller-78f5844ddb-fvn26 secretgen-controller panic({0x131cda0, 0x164d9d0})
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      runtime/panic.go:1038 +0x215
secretgen-controller-78f5844ddb-fvn26 secretgen-controller github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator.GenerateInputs.Add({{0x13f7240, 0xc00049ca80}}, 0x0)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator/generate_inputs.go:23 +0x65
secretgen-controller-78f5844ddb-fvn26 secretgen-controller github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator.(*CertificateReconciler).createSecret(0xc000776a50, {0x16799b8, 0xc00089a2a0}, {{0x0, 0x0}, {0x14a0bf4, 0x9}, {0x0, 0x0, 0x0}, ...}, ...)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator/certificate_reconciler.go:119 +0x45e
secretgen-controller-78f5844ddb-fvn26 secretgen-controller github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator.(*CertificateReconciler).reconcile(0xc000776a50, {0x16799b8, 0xc00089a2a0}, 0x0)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator/certificate_reconciler.go:79 +0x29d
secretgen-controller-78f5844ddb-fvn26 secretgen-controller github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator.(*CertificateReconciler).Reconcile(0xc000776a50, {0x16799b8, 0xc00089a2a0}, {{{0xc00064f0e0, 0x138c9c0}, {0xc00064f0d0, 0xc000812340}}})
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator/certificate_reconciler.go:70 +0x395
secretgen-controller-78f5844ddb-fvn26 secretgen-controller sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00076f040, {0x1679910, 0xc0004ac4c0}, {0x1368e00, 0xc000289000})
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263 +0x303
secretgen-controller-78f5844ddb-fvn26 secretgen-controller sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00076f040, {0x1679910, 0xc0004ac4c0})
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235 +0x205
secretgen-controller-78f5844ddb-fvn26 secretgen-controller sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1({0x1679910, 0xc0004ac4c0})
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198 +0x46
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0x25
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fa4be29dcf8)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155 +0x67
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0, {0x16542e0, 0xc00089a120}, 0x1, 0xc0000af4a0)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156 +0xb6
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x2, 0x3b9aca00, 0x0, 0x80, 0x1000000020002)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133 +0x89
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext({0x1679910, 0xc0004ac4c0}, 0xc00057a0e0, 0x0, 0x0, 0x0)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0x99
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/wait.UntilWithContext({0x1679910, 0xc0004ac4c0}, 0xc000614c60, 0xc00014ef68)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99 +0x2b
secretgen-controller-78f5844ddb-fvn26 secretgen-controller created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:195 +0x4b0
- secretgen-controller-78f5844ddb-fvn26 › secretgen-controller
```

**What did you expect:**
[A description of what was expected]

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

**Environment:**

- secretgen-controller version (execute `kubectl get deployment -n secretgen-controller secretgen-controller -o yaml` and the annotation is `kbld.k14s.io/images`):
```
kbld.k14s.io/images: |
      - origins:
        - resolved:
            tag: v0.8.0_vmware.1
            url: projects-stg.registry.vmware.com/tkg/secretgen-controller:v0.8.0_vmware.1
        - preresolved:
            url: registry.tanzu.vmware.com/tanzu-cluster-essentials/cluster-essentials-bundle@sha256:bda67d55ade826092884f49243a797e1e2a946ddbc056b37de7b8a8dedce729a
        url: registry.tanzu.vmware.com/tanzu-cluster-essentials/cluster-essentials-bundle@sha256:bda67d55ade826092884f49243a797e1e2a946ddbc056b37de7b8a8dedce729a
    secretgen-controller.carvel.dev/version: v0.8.0
```

- Kubernetes version (use `kubectl version`)
```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-24T22:06:50Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
```

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by vicmarbev**
Fixes #84 

When the secret we want to create does not have annotations, the map object received by GenerateInputs.Add is empty. To be able to process certificates with or without annotations, we check the length of the map before marshalling it.

Signed-off-by: Víctor Martínez Bevià <vicmarbev@gmail.com>

### CODE REVIEW

File: pkg/generator/generate_inputs.go [hunk 1]
```diff
@@ -16,11 +16,13 @@ type GenerateInputs struct {
...
 func (i GenerateInputs) Add(anns map[string]string) {
-	bs, err := json.Marshal(i.inputs)
-	if err != nil {
-		panic("Cannot marshal generate inputs")
+	if len(anns) > 0 {
+		bs, err := json.Marshal(i.inputs)
+		if err != nil {
+			panic("Cannot marshal generate inputs")
+		}
+		anns[GenerateInputsAnnKey] = string(bs)
```
Comment (joe-kimmel-vmw) [inline pkg/generator/generate_inputs.go]: @vicmarbev - First: Thank you for contributing!

I agree that this will fix the crash but I'm honestly not sure whether this will lead to the desired behavior, as I haven't spent enough time understanding this part of the controller at all yet.

The way this is written, I think we won't add the "generate-inputs" annotation in some cases, and my suspicion is that this will lead to incorrect behavior or "surprising UX" someplace else.

  Do you think we should always add our "secretgen.k14s.io/generate-inputs" annotation even if the secret had no other previous annotations?

Comment (vicmarbev) [reply pkg/generator/generate_inputs.go]: Sure! What should be the value for  `secretgen.k14s.io/generate-inputs` if no annotations are provided?

Comment (joe-kimmel-vmw) [reply pkg/generator/generate_inputs.go]: @vicmarbev It looks like one way out of this is to try to ensure that the annotations on the secret aren't nil when we call this `Add` function: https://github.com/vmware-tanzu/carvel-secretgen-controller/blob/develop/pkg/generator/certificate_reconciler.go#L119

(1)
Above that line we could check whether the Secret object has nil annotations and then instantiate an empty map into its Annotations field.

(2)
Additionally it would be great to change this panic to be more informative that the caller is calling the function in an unanticipated way. For example we talked with @joaopapereira about what imgpkg does, and it might be more informative to have an error message saying something like, "Internal inconsistency: <function name> called with nil param". 

(3)
Finally, to be the most cloud-native-y and live our best lives, we should probably convert this from a panic into a "comma, error" idiom and have the reconciler (linked above) mark the resource as "failed to reconcile" if the `Add` function can't execute. 


For the scope of this PR please definitely do (1) above.  In terms of making future failures more graceful, we'd prefer to skip (2) and go straight to (3), but given that this code is really only currently called in one place, if you want to resubmit with just (1) implemented that will be an incremental improvement.

re. your question about the appropriate value of the annotation - honestly it looks like this part of the code isn't fully finished since nobody ever finished the TODO in the `UpdateSecret` method.  The current `bs` value is fine.

cc @neil-hickey @joaopapereira

**Comment by vicmarbev** [comment]
What do you think of these changes, @joe-kimmel-vmw? I'd like to test all cases, but I can't cover the unmarshal error without wrapping it in a function I can mock.

File: pkg/generator/generate_inputs_test.go [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+import (
+	"testing"
+
+	"github.com/stretchr/testify/assert"
+	"github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator"
+)
+
+func TestAddSucceedsWithEmptyAnnotations(t *testing.T) {
+	err := generator.GenerateInputs{}.Add(nil)
+	assert.Equal(t, nil, err)
```
Comment (joe-kimmel-vmw) [inline pkg/generator/generate_inputs_test.go]: here you're testing that there's no assertions,  but i think that the map you created on line 22 (https://github.com/vmware-tanzu/carvel-secretgen-controller/pull/92/files#diff-c07fd47e85b29b850abf835f11f15dadd5a05dee6387a5aaa4883e2eabf63960R22) goes out of scope when the function returns.  That was why we pointed you towards the place that calls the function as likely the right place to create the map. 

  Can you change this test to assert that if it's called with a Secret with no annotations, then the annotation we added in that function is actually present on the secret afterwards?

Comment (vicmarbev) [reply pkg/generator/generate_inputs_test.go]: Yep, [my bad](https://dave.cheney.net/2017/04/29/there-is-no-pass-by-reference-in-go#:~:text=But%20maps%20and%20channels%20are%20references%2C%20right%3F). The initialization renders the change out of scope for the original map. I'll give it another go in a few hours following your recommendations, thanks for the pointers!

**Comment by vicmarbev** [comment]
Ok! The last change moves the modification of the certificate annotations to the certificate_reconciler. I've kept the GenerateInputs unit tests to cover unknowns and added annotation checking to the existing certificate e2e test.

**Comment by joe-kimmel-vmw** [comment]
thanks! - now you're running afoul of our linter 😆 - because you changed the code it wants a documentation string above the method.  --   i think in this case maybe you have enough context to write something nominally helpful?  or since the code barely does anything at all maybe you'd rather add a nolint comment (i think either `// nolint:golint` or `// nolint:revive`)

**Comment by joe-kimmel-vmw** [comment]
btw @vicmarbev - I see you're contributing changes to a few of the Carvel tools - feel free to drop in to the Carvel Community meeting?  We're having one approximately "now" so the next one will be in two weeks: 
see : https://carvel.dev/community/

Thanks for all your contributions!

**Comment by vicmarbev** [comment]
Just trying to give back to the community! We use Tanzu extensively at work 😄 .

File: pkg/generator/certificate_reconciler.go [hunk 3]
```diff
@@ -116,7 +116,15 @@ func (r *CertificateReconciler) createSecret(ctx context.Context, params certPar
 
 	newSecret := secret.AsSecret()
 
-	GenerateInputs{params}.Add(newSecret.Annotations)
+	if newSecret.Annotations == nil {
+		newSecret.Annotations = map[string]string{
+			"secretgen.k14s.io/generate-inputs": "",
```
Comment (joe-kimmel-vmw) [inline pkg/generator/certificate_reconciler.go]: thanks! this PR is almost ready.  i think we just need to remove this line. here's a little reasoning.: 

1.) we're about to call the `Add` method, and it will set the annotation. No need to do it in advance.
2.) The annotation's key name here is hardcoded straight into the string, but it's actually a constant in the other file, so we don't need to leak that information or duplicate it here. 

so anyway please just make an empty map `{}` and that should take care of it.

**Comment by joe-kimmel-vmw** [comment]
> We use Tanzu extensively at work 😄 .

@vicmarbev  Would you (and/or teammates) be willing to do a 45 minute chat with us about how you're using the tools and what else you'd like to see in them?

**Comment by vicmarbev** [comment]
Sure! Next week works for me. We are at UTC+2, though.

**Comment by joe-kimmel-vmw** [comment]
@vicmarbev What's the best way to reach you that isn't github?    Can we catch up in https://kubernetes.slack.com/archives/CH8KCCKA5. ?
